review: guide/features
vitejs/docs-cn pull request #154
Opened 2021-06-16 08:11 UTC by Ardor-Zhang

2021-06-17 14:45 UTC, ShenQingchuan commented on guide/features.md
> +上面的代码会在浏览器中抛出一个错误。Vite 将在的所有被加载的源文件中检测此类裸模块导入，并执行以下操作:
```suggestion
上面的代码会在浏览器中抛出一个错误。Vite 将对所有被加载的源文件检测此类裸模块导入，并执行以下操作:
```

2021-06-17 14:47 UTC, ShenQingchuan commented on guide/features.md
> +Vite 仅执行 `.ts` 文件的转译工作，并 **不** 执行任何类型检查。并假设类型检查已经被你的 IDE 或构建过程接管了（你可以在构建脚本中运行 `tsc --noEmit` 或者安装 `vue-tsc` 然后运行 `vue-tsc --noEmit` 来对你的 `*.vue` 文件做类型检查）。
```suggestion
Vite 仅执行 `.ts` 文件的转译工作，并 **不** 执行任何类型检查。并假设类型检查已经被你的 IDE 或构建过程接管了。（你可以在构建脚本中运行 `tsc --noEmit` 或者安装 `vue-tsc` 然后运行 `vue-tsc --noEmit` 来对你的 `*.vue` 文件做类型检查）
```

2021-06-17 14:49 UTC, ShenQingchuan commented on guide/features.md
> +`.jsx` 和 `.tsx` 文件同样开箱即用。JSX 的转译同样是通过 [esbuild](https://esbuild.github.io)，默认为 React 16 风格。期望在 esbuild 中支持React 17 风格的 JSX 请看 [这里](https://github.com/evanw/esbuild/issues/334)。
```suggestion
`.jsx` 和 `.tsx` 文件同样开箱即用。JSX 的转译同样是通过 [esbuild](https://esbuild.github.io)，默认为 React 16 风格。期望在 esbuild 中支持 React 17 风格的 JSX 请看 [这里](https://github.com/evanw/esbuild/issues/334)。
```

2021-06-17 14:51 UTC, ShenQingchuan commented on guide/features.md
> +`init` 函数还可以将传递给 `WebAssembly.instantiate`  的导入对象作为其第二个参数：
```suggestion
`init` 函数还可以将传递给 `WebAssembly.instantiate` 的导入对象作为其第二个参数：
```

2021-06-17 14:51 UTC, ShenQingchuan commented on guide/features.md
> +> 下面所罗列的功能会自动应用为构建过程的一部分，除非你想禁用它们，否则没有必要显示配置。
```suggestion
> 下面所罗列的功能会自动应用为构建过程的一部分，除非你想禁用它们，否则没有必要显式配置。
```

2021-06-17 14:57 UTC, ShenQingchuan commented on guide/features.md
> +Vite 会为入口 chunk 和它们在打包出的 HTML 中直接引入自动生成的 `<link rel="modulepreload">` 指令。
<h2 style="color: red"><strong>请求删除</strong></h2>

> 原文：
> Vite automatically generates <link rel="modulepreload"> directives for **entry chunks** and **their direct imports** in the built HTML.

这里是双宾语：
分别是 “**入口 chunk**” 和 “**他们在打包出的 HTML 中的直接引入**”

入口 chunk 是一个很容易理解的 名词短语 --- 对应原文中的 entry chunk
后面这个很长的复杂短语，中心词是 “引入”，对应原文的 imports

2021-06-17 15:00 UTC, ShenQingchuan commented on guide/features.md
> +在无优化的情境下，当异步 chunk `A` 被导入时，浏览器将必须请求和解析 `A`，然后它才能弄清楚它也需要那个共用 chunk `C`。这会导致额外的网络往返：
```suggestion
在无优化的情境下，当异步 chunk `A` 被导入时，浏览器将必须请求和解析 `A`，然后它才能弄清楚它也需要共用 chunk `C`。这会导致额外的网络往返：
```

2021-06-17 15:01 UTC, ShenQingchuan requested changes
请查看 Comment 考虑更改。

2021-06-20 04:08 UTC, Ardor-Zhang commented
> 请查看 Comment 考虑更改。

没问题！感谢！！

2021-06-20 04:17 UTC, Ardor-Zhang commented on guide/features.md
> +上面的代码会在浏览器中抛出一个错误。Vite 将在的所有被加载的源文件中检测此类裸模块导入，并执行以下操作:
首先去掉定语修改为以下： 
`Vite 将会检测到文件中的此类裸模块导入，并执行以下操作:`

然后添加上定语
`Vite 将会检测到_所有被加载的源_文件中的此类裸模块导入，并执行以下操作`

2021-06-20 04:33 UTC, Ardor-Zhang commented on guide/features.md
> +Vite 会为入口 chunk 和它们在打包出的 HTML 中直接引入自动生成的 `<link rel="modulepreload">` 指令。
之前在修改这里的时候也纠结了，按照直译的话的确是应该`their direct imports in the HTML`, 但是为什么我会这样改是因为`link` 的缘故。
看了你的解释后，才觉得可能是在 chunk js 和 html 的”自动引入“脚本中都会自动的插入这段 `link`，谢谢！！

2021-06-20 04:44 UTC, Ardor-Zhang commented
> 请查看 Comment 考虑更改。
已修改，麻烦看一下！！

2021-06-22 04:26 UTC, ShenQingchuan commented
LGTM.

2021-06-22 04:26 UTC, merged