docs: translation enhancement, typos in index.md
vitejs/docs-cn pull request #17
Opened 2021-02-18 09:52 UTC by Ivocin

2021-02-18 10:17 UTC, Ivocin commented on guide/index.md
> +Vite 是“有主见的”，提供了开箱即用的合理默认配置，但 Vite 通过它的 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 具有了高度的可扩展性，并支持全类型。
opinionated 暂译为 “有主见的”，像 [Prettier - Opinionated Code Formatter ](https://prettier.io/)  也强调自己是 opinionated，不知道翻译成带有贬义的“固执己见的”是否合适。

2021-02-18 10:49 UTC, KnowsCount commented on guide/index.md
> +Vite 是“有主见的”，提供了开箱即用的合理默认配置，但 Vite 通过它的 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 具有了高度的可扩展性，并支持全类型。
Oxford 给出的定义是

> characterised by conceited assertiveness and dogmatism.

真是……这些东西怎么给自己用贬义的……预计就想表达自己是那种很乔布斯式的东西。

2021-02-18 13:06 UTC, Ivocin commented on guide/index.md
> +Vite 是“有主见的”，提供了开箱即用的合理默认配置，但 Vite 通过它的 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 具有了高度的可扩展性，并支持全类型。
确实是，感觉 Apple 也是 opinionated 的代表。

2021-02-19 15:54 UTC, ShenQingchuan requested changes

2021-02-19 15:54 UTC, ShenQingchuan commented on guide/index.md
> +Vite 是“有主见的”，提供了开箱即用的合理默认配置，但 Vite 通过它的 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 具有了高度的可扩展性，并支持全类型。
**仅作讨论**

这样翻译阅读起来体验感觉不是太好，有点生硬，这里似乎不应如此直译

参见 Wiki 手册：翻译时应相对在语言色彩上表达得相对克制。

```suggestion
Vite 意在提供开箱即用的合理配置，同时 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 带来了高度的可扩展性，和完全的类型化支持。
```

2021-02-20 12:33 UTC, Ivocin commented on guide/index.md
> +Vite 是“有主见的”，提供了开箱即用的合理默认配置，但 Vite 通过它的 [插件 API](./api-plugin) 和 [JavaScript API](./api-javascript) 具有了高度的可扩展性，并支持全类型。
> 参见 Wiki，我们的翻译方式、用语的语言色彩应保持相对克制。
> 
> 仅作讨论与参考。

好的，这样译比较舒服了。

2021-02-20 12:41 UTC, merged