fix: re translate about "The Problems"
vitejs/docs-cn pull request #34
Opened 2021-02-21 04:36 UTC by wjq990112

润色了一下文档的 “现实问题” 部分，先前的翻译感觉稍有些生硬。

2021-02-21 05:10 UTC, KnowsCount approved these changes
哈哈哈哈哈这很多我在 #14 中改过，但是那个不小心格式化了一下文档，所以没 merge 进去。你可以参考下。

2021-02-21 06:25 UTC, Ivocin requested changes

2021-02-21 06:25 UTC, Ivocin commented on guide/why.md
> +在浏览器支持 ES Module 之前，开发者没有以模块化的方式开发 JavaScript 的原生机制。这也是出现 “打包” 这个概念的原因：使用工具抓取、处理和链接我们的源代码模块到文件中，使其可以运行在浏览器中。
ES Module -> ES 模块，这个可以翻译
可以和尤大的[译法](https://zhuanlan.zhihu.com/p/351147547)保持一致。
源代码 -> 源码

2021-02-21 06:25 UTC, Ivocin commented on guide/why.md
> +Vite 旨在利用生态系统中的新进展解决上述问题：浏览器开始原生支持 ES Module，越来越多 JavaScript 工具使用编译型语言编写。
ES Module 同上

2021-02-21 06:25 UTC, Ivocin commented on guide/why.md
> +但是，随着我们开始构建越来越大型的应用程序，需要处理的 JavaScript 代码量也呈指数级增长。大型项目包含数千个模块的情况并不少见。我们开始遇到性能瓶颈 —— 基于 JavaScript 开发的工具通常需要很长时间（甚至是几分钟！）才能启动开发服务器，即使使用 HMR，文件修改后的效果也需要几秒钟才能在浏览器中反映出来。如此循环往复，迟钝的反馈会极大地影响开发者的开发效率和幸福感。
应用程序 -> 应用

参考 Vue 的[中文文档约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E4%B8%AD%E6%96%87%E6%9C%AF%E8%AF%AD%E7%BA%A6%E5%AE%9A)

2021-02-21 06:26 UTC, Ivocin commented on guide/why.md
> +但是，随着我们开始构建越来越大型的应用程序，需要处理的 JavaScript 代码量也呈指数级增长。大型项目包含数千个模块的情况并不少见。我们开始遇到性能瓶颈 —— 基于 JavaScript 开发的工具通常需要很长时间（甚至是几分钟！）才能启动开发服务器，即使使用 HMR，文件修改后的效果也需要几秒钟才能在浏览器中反映出来。如此循环往复，迟钝的反馈会极大地影响开发者的开发效率和幸福感。
发现整个仓库里译文有多处“应用程序”，可以在这个 pr 都顺便提交了

2021-02-21 06:44 UTC, wjq990112 commented on guide/why.md
> +在浏览器支持 ES Module 之前，开发者没有以模块化的方式开发 JavaScript 的原生机制。这也是出现 “打包” 这个概念的原因：使用工具抓取、处理和链接我们的源代码模块到文件中，使其可以运行在浏览器中。
get，对于这一块翻译的要求不太了解，等会修改回来。

2021-02-21 06:54 UTC, wjq990112 commented
翻译组有没有相关的群聊，留个联系方式加入群聊中，后续应该会一起参与一些翻译工作。

2021-02-21 07:06 UTC, Ivocin approved these changes

2021-02-21 07:07 UTC, Ivocin commented
> 翻译组有没有相关的群聊，留个联系方式加入群聊中，后续应该会一起参与一些翻译工作。

有没有，想加一个方便交流 @ShenQingchuan  @KnowsCount

2021-02-21 07:58 UTC, KnowsCount commented
> > 翻译组有没有相关的群聊，留个联系方式加入群聊中，后续应该会一起参与一些翻译工作。
> 
> 有没有，想加一个方便交流 @ShenQingchuan @KnowsCount

我个人不清楚。预计是没有，等 @ShenQingchuan 创建一个？

2021-02-21 14:33 UTC, wjq990112 commented
> > > 翻译组有没有相关的群聊，留个联系方式加入群聊中，后续应该会一起参与一些翻译工作。
> > 
> > 
> > 有没有，想加一个方便交流 @ShenQingchuan @KnowsCount
> 
> 我个人不清楚。预计是没有，等 @ShenQingchuan 创建一个？

要不我创建一个拉大家进来？ @Ivocin @KnowsCount

2021-02-21 15:23 UTC, Ivocin commented
> > > > 翻译组有没有相关的群聊，留个联系方式加入群聊中，后续应该会一起参与一些翻译工作。
> > > 
> > > 
> > > 有没有，想加一个方便交流 @ShenQingchuan @KnowsCount
> > 
> > 
> > 我个人不清楚。预计是没有，等 @ShenQingchuan 创建一个？
> 
> 要不我创建一个拉大家进来？ @Ivocin @KnowsCount

可以啊

2021-02-21 15:24 UTC, Ivocin approved these changes

2021-02-22 09:26 UTC, ShenQingchuan commented
可以由大家创建一个

2021-02-22 09:26 UTC, merged