fix: polish Get Started
vitejs/docs-cn pull request #42
Opened 2021-03-02 05:49 UTC by Wzb3422

2021-03-02 07:29 UTC, Ivocin requested changes
润色的很棒，一些建议在 Comment 里。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +Vite 将 `index.html` 视为源码和模块图的一部分。你的 JavaScript 代码将会通过 `<script type="module" src="...">` 来引用。甚至内联引入 JavaScript 的 `<script type="module" src="...">` 和引用 CSS 的 `<link href>` 也能享受 Vite 相关的特性。另外，`index.
这句话的意思的内联的 js 和 css 可以利用 Vite 的特有功能被解析。“也能享受 Vite 相关的特性” 体现不出这个意思。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +Vite 将 `index.html` 视为源码和模块图的一部分。你的 JavaScript 代码将会通过 `<script type="module" src="...">` 来引用。甚至内联引入 JavaScript 的 `<script type="module" src="...">` 和引用 CSS 的 `<link href>` 也能享受 Vite 相关的特性。另外，`index.
“你的 JavaScript 代码将会通过 `<script type="module" src="...">` 来引用。”  
不符合文意，原文意思是 Vite 解析了 `<script type="module" src="..."> ` 这个标签，这个标签指向你的 JavaScript 源码。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +与静态 HTTP 服务器类似，Vite 也有 “根目录” 的概念。你会看到它在整个文档中用 `<root>` 表示。源码中的绝对 URL 路径将以项目的 “根” 作为基础来解析，因此你可以像在普通的静态文件服务器上一样编写代码（并且功能更强大！）。Vite 还能够处理依赖关系，解析处于根目录外的文件位置，这使得它即使在基于 monorepo 的方案中也十分有用。
原文： Vite has the concept of a "root directory" from which your files are served from. 
这里漏掉了 which your files are served from.  这段话。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +## 命令行
Command Line Interface 也就是我们常说的 CLI ，译为 “命令行界面” 比较合适。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +如果你迫不及待想要体验最新的特性，可以自行克隆 [vite 仓库](https://github.com/vitejs/vite) 到本地机器上然后自行将其链接（将需要 [Yarn 1.x](https://classic.yarnpkg.com/lang/en/)）：
特性 -> 功能
文档内 feature 统一译为 “功能”，与尤大的[译法](https://zhuanlan.zhihu.com/p/351147547)保持一致。

2021-03-02 07:29 UTC, Ivocin commented on guide/index.md
> +然后，回到你的 vite 项目并运行 `yarn link vite`。重新启动开发服务器（`yarn dev`）来体验新特性吧！
特性 -> 功能
同上

2021-03-02 14:46 UTC, Wzb3422 commented on guide/index.md
> +与静态 HTTP 服务器类似，Vite 也有 “根目录” 的概念。你会看到它在整个文档中用 `<root>` 表示。源码中的绝对 URL 路径将以项目的 “根” 作为基础来解析，因此你可以像在普通的静态文件服务器上一样编写代码（并且功能更强大！）。Vite 还能够处理依赖关系，解析处于根目录外的文件位置，这使得它即使在基于 monorepo 的方案中也十分有用。
修改后的我选择的译法是：Vite 也有 “根目录” 的概念，即文件被提供的位置。
但这种译法也有些拗口，略带翻译腔。也没想到更好的译法了。
请教下大家的意见～

2021-03-02 14:46 UTC, Wzb3422 commented on guide/index.md
> +## 命令行
已修改

2021-03-02 14:47 UTC, Wzb3422 commented on guide/index.md
> +如果你迫不及待想要体验最新的特性，可以自行克隆 [vite 仓库](https://github.com/vitejs/vite) 到本地机器上然后自行将其链接（将需要 [Yarn 1.x](https://classic.yarnpkg.com/lang/en/)）：
已修改，下文的一并改好了。

2021-03-03 08:28 UTC, Ivocin commented on guide/index.md
> +与静态 HTTP 服务器类似，Vite 也有 “根目录” 的概念。你会看到它在整个文档中用 `<root>` 表示。源码中的绝对 URL 路径将以项目的 “根” 作为基础来解析，因此你可以像在普通的静态文件服务器上一样编写代码（并且功能更强大！）。Vite 还能够处理依赖关系，解析处于根目录外的文件位置，这使得它即使在基于 monorepo 的方案中也十分有用。
有翻译腔的原因可能是“被提供“这种被动语态，英文被动语态比较多，中文转为主动比较自然。
原来的“这个根目录是指你的文件运行的位置” 将“文件被服务”译为“文件（在服务器）运行”是符合文意的。

2021-03-04 13:49 UTC, ShenQingchuan approved these changes

2021-03-04 13:49 UTC, merged