fixed: config/index
vitejs/docs-cn pull request #44
Opened 2021-03-05 13:55 UTC by okbug

2021-03-05 23:29 UTC, Ivocin approved these changes

2021-03-06 07:01 UTC, ShenQingchuan requested changes

2021-03-06 07:01 UTC, ShenQingchuan commented on config/index.md
> +  当使用文件系统路径的别名时，请始终使用绝对路径。相对路径的别名值将按原样使用导致不会被解析到文件系统路径中。
**仅作讨论**

这里是不是润色，意译一下更好 ：
```suggestion
  当使用文件系统路径的别名时，请始终使用绝对路径。相对路径的别名值将按原样使用因而无法被正常解析。
```

2021-03-06 07:01 UTC, ShenQingchuan commented on config/index.md
> +  作为静态资源服务的文件夹。这个目录中的文件会在开发中被服务于 `/`，在dev模式时，会被拷贝到 `outDir` 的根目录，并没有转换，永远只是复制到这里。该值可以是文件系统的绝对路径，也可以是相对于项目的根目录路径。
或者直接改为 “开发模式”

2021-03-08 12:02 UTC, okbug reviewed
ok

2021-03-11 12:19 UTC, ShenQingchuan commented
这个 Pull Request 后续是否有时间跟进进展呢？

2021-03-13 01:45 UTC, okbug commented
> 这个 Pull Request 后续是否有时间跟进进展呢？

如何跟进?

2021-03-15 06:21 UTC, wjq990112 commented
> > 这个 Pull Request 后续是否有时间跟进进展呢？
> 
> 如何跟进?

看下 CR，修改一下标注的部分。

2021-03-20 06:53 UTC, ShenQingchuan commented on config/index.md
> +  作为静态资源服务的文件夹。这个目录中的文件会在开发中被服务于 `/`，在dev模式时，会被拷贝到 `outDir` 的根目录，并没有转换，永远只是复制到这里。该值可以是文件系统的绝对路径，也可以是相对于项目的根目录路径。
```suggestion
  作为静态资源服务的文件夹。这个目录中的文件会在开发中被服务于 `/`，在开发模式时，会被拷贝到 `outDir` 的根目录，并没有转换，永远只是复制到这里。该值可以是文件系统的绝对路径，也可以是相对于项目的根目录路径。
```

2021-03-20 06:54 UTC, ShenQingchuan commented on config/index.md
> +  将会被传递到 `@rollup/plugin-alias` 作为 [entries](https://github.com/rollup/plugins/tree/master/packages/alias#entries)的选项。也可以是一个对象，或一个 `{ find, replacement }` 的数组.
```suggestion
  将会被传递到 `@rollup/plugin-alias` 作为 [entries](https://github.com/rollup/plugins/tree/master/packages/alias#entries) 的选项。也可以是一个对象，或一个 `{ find, replacement }` 的数组.
```

2021-03-20 06:56 UTC, ShenQingchuan approved these changes

2021-03-20 06:57 UTC, ShenQingchuan commented
由于此 PR 时间太久，会将可取的润色、改动强制更改。

**特此告知**。

2021-03-20 06:58 UTC, merged