fix: adjust title
vitejs/docs-cn pull request #93
Opened 2021-04-20 02:37 UTC by Justineo

这个文档是描述 Vite 本身的，不用加上“官方中文文档”字样。

2021-04-20 03:45 UTC, QC-L commented
这个是我们讨论过的，因为被其他平台 copy 了， google 一下 vite 中文~

2021-04-20 11:00 UTC, KnowsCount commented
#84 中内容供参考：https://github.com/vitejs/docs-cn/pull/84#pullrequestreview-637465128

2021-04-20 11:00 UTC, KnowsCount requested changes
#84 中内容供参考：https://github.com/vitejs/docs-cn/pull/84#pullrequestreview-637465128

2021-04-20 12:30 UTC, Justineo commented
原来如此，谢谢。这个用插件怎么解决？@QC-L

2021-04-21 01:11 UTC, QC-L commented
要从 vitepress 下手，写 markdown-it 部分的插件。

2021-04-21 01:28 UTC, closed without merging