docs(guide/env-and-mode): review completed
vitejs/docs-cn pull request #99
Opened 2021-05-04 03:47 UTC by ATQQ

2021-05-04 04:07 UTC, KnowsCount commented on guide/env-and-mode.md
> +- `.env.*.local` 文件应是本地的，可以包含敏感变量。你应该将`.local`添加到你的`.gitignore`中，以避免它们被git检入。
```suggestion
- `.env.*.local` 文件应是本地的，可以包含敏感变量。你应该将`.local`添加到你的`.gitignore`中，以避免它们被 git 检入。
```

英文与中文间记得空格。

2021-05-04 04:08 UTC, KnowsCount commented on guide/env-and-mode.md
> +现在，你的staging 应用应该具有类似于生产的行为，但显示的标题与生产环境不同。
```suggestion
现在，你的 staging 应用应该具有类似于生产的行为，但显示的标题与生产环境不同。
```

2021-05-04 04:09 UTC, KnowsCount commented on guide/env-and-mode.md
> +默认情况下，Vite为`import.meta.env`提供了类型定义。随着在 `.env[mode]` 文件中自定义了越来越多的环境变量，你可能想要在代码中获取这些以 `VITE_` 为前缀的用户自定义环境变量的 TypeScript 智能提示。
```suggestion
默认情况下，Vite 为`import.meta.env`提供了类型定义。随着在 `.env[mode]` 文件中自定义了越来越多的环境变量，你可能想要在代码中获取这些以 `VITE_` 为前缀的用户自定义环境变量的 TypeScript 智能提示。
```

2021-05-04 04:10 UTC, KnowsCount commented on guide/env-and-mode.md
> +然而，重要的是要理解**模式**是一个更广泛的概念，而不仅仅是开发和生产。一个典型的例子是，你可能希望有一个 “staging”（预发布|预上线） 模式，它应该具有类似于生产的行为，但环境变量与生产环境略有不同。
```suggestion
然而，重要的是要理解 **模式** 是一个更广泛的概念，而不仅仅是开发和生产。一个典型的例子是，你可能希望有一个 “staging”（预发布|预上线） 模式，它应该具有类似于生产的行为，但环境变量与生产环境略有不同。
```

参见 wiki。

2021-05-04 04:10 UTC, KnowsCount commented on guide/env-and-mode.md
> +- **`import.meta.env.BASE_URL`**: {string} 部署应用时的基本URL. 他由[`base` 配置项](/config/#base)决定。
```suggestion
- **`import.meta.env.BASE_URL`**: {string} 部署应用时的基本URL。它由[`base` 配置项](/config/#base)决定。
```

2021-05-04 04:12 UTC, KnowsCount requested changes
嘿嘿，翻译的这么好，可是有些地方不符合我们的规范。

2021-05-04 04:49 UTC, ATQQ commented
> 嘿嘿，翻译的这么好，可是有些地方不符合我们的规范。

安排 :smiling_face_with_three_hearts:

2021-05-04 06:12 UTC, KnowsCount commented
你可以直接通过我对你代码的评论 commit 进去的。

---

并且，那个句号后面多了个空格。

2021-05-04 06:40 UTC, ATQQ commented
> 你可以直接通过我对你代码的评论 commit 进去的 (●°u°●)​ 」。就是……按那个 add suggestion to batch。 然后一起 commit。
> 
> 并且，那个句号后面多了个空格。

哈哈，没注意到，下次一定  :cry:

2021-05-04 07:17 UTC, KnowsCount approved these changes

2021-05-05 06:57 UTC, QC-L commented on guide/env-and-mode.md
> +# 环境变量和模式
需要加锚点

2021-05-05 07:05 UTC, QC-L commented on guide/env-and-mode.md
> +# 环境变量和模式
参考下 main 分支下的文档

2021-05-05 07:19 UTC, KnowsCount commented on guide/env-and-mode.md
> +# 环境变量和模式
```suggestion
# 环境变量和模式 {#env-variables-and-modes}
```

类似这样。

2021-05-05 07:22 UTC, ATQQ commented on guide/env-and-mode.md
> +# 环境变量和模式
get ，没在wiki中看到这个

2021-05-05 10:31 UTC, QC-L approved these changes

2021-05-05 10:32 UTC, merged